apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
  labels:
    app: grafana-app
spec:
  selector:
    app: grafana-app
  type: LoadBalancer
  loadBalancerIP: 192.168.99.241
  ports:
  - port: 3000
    targetPort: 3000
    name: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana
        image: grafana-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: grafana-secret
      securityContext:
        fsGroup: 472