apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-app
      #tier: frontend
  template:
    metadata:
      name: phpmyadmin-pod
      labels:
        app: phpmyadmin-app
        #tier: frontend
    spec:
      containers:
        - name: phpmyadmin
          image: php-image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: a1234