apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  ports:
    - name: phpmyadmin
      targetPort: 5000
      port: 5000
  selector:
    app: phpmyadmin-app
  type: LoadBalancer
  loadBalancerIP: 192.168.99.239
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-app
  template:
    metadata:
      name: phpmyadmin-pod
      labels:
        app: phpmyadmin-app
    spec:
      containers:
        - name: phpmyadmin
          image: php-image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PMA_HOST
              value: mysql-service
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: a1234
